version: 0.2

phases:
  install:
    commands:
      - echo "Iniciando o build..."
      - go version
      - ls
  build:
    commands:
      - echo "Compilando o código Go..."
      - go build -o projeto_go main.go
artifacts:
  files:
    - main

